---
- name: Install nmtrust
  kewlfft.aur.aur:
      name: nmtrust-git
  become: yes
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Create nmtrust config directory
  file:
      path: /etc/nmtrust
      state: directory

- name: Push trusted network list
  template:
      src: trusted_networks.j2
      dest: /etc/nmtrust/trusted_networks

- name: Verify trusted unit list exists
  copy:
      content: ""
      dest: /etc/nmtrust/trusted_units
      force: false
