---
- name: Install chrony
  pacman: name=chrony state=present

- name: Install chrony networkmanager dispatcher
  kewlfft.aur.aur:
    name: networkmanager-dispatcher-chrony
  become: yes
  become_user: "{{ aur.user }}"
  tags:
    - aur
    - networkmanager

- name: Push chrony configuration file
  copy: src=chrony.conf dest=/etc/chrony.conf
  notify:
    - restart chrony

- name: Enable and start chrony
  service: name=chronyd.service enabled=yes state=started
