---
- name: Install Fedora systemd-oomd configuration
  kewlfft.aur.aur:
      name: systemd-oomd-defaults
  become: yes
  become_user: "{{ aur.user }}"
  notify:
    - reload systemd config
  tags:
    - aur

- name: Enable and start systemd-oomd
  service:
    name: systemd-oomd.service
    enabled: yes
    state: started
