---
- name: Install taskwarrior
  pacman: name=task state=present

- name: Install timewarrior
  pacman: name=timew state=present
  notify:
    - refresh holidays

- name: Install taskopen
  kewlfft.aur.aur:
    name: taskopen
  become: yes
  become_user: "{{ aur.user }}"
  tags:
    - aur
