---
- name: Install vdirsyncer
  pacman:
    name: vdirsyncer
    state: present

- name: Install khard
  pacman:
    name: khard
    state: present

- name: Install khal
  pacman:
    name: khal
    state: present

- name: Install etesync-dav
  kewlfft.aur.aur:
      name: etesync-dav
  become: yes
  become_user: "{{ aur.user }}"
  tags:
    - aur
  when: etesync is defined and etesync == True

- name: Push etesync-dav service file
  copy:
    src: etesync-dav.service
    dest: /etc/systemd/user/etesync-dav.service
  notify:
    - reload systemd config
  when: etesync is defined and etesync == True
