---
- name: Install calibre
  pacman: name=calibre state=present

- name: Jail calibre
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/calibre
        state=link
  tags:
    - firejail

- name: Jail ebook-viewer
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/ebook-viewer
        state=link
  tags:
    - firejail

- name: Install libgourou
  aur:
    name: gourou
    user: "{{ user.name }}"
  tags:
    - aur
