---
- name: Install dictd
  pacman:
    name: dictd
    state: present

- name: Install flex
  pacman:
    name: flex
    state: present

- name: Install GNU Collaborative International Dictionary of English
  kewlfft.aur.aur:
    name: dict-gcide
    use: makepkg
    skip_pgp_check: yes
  become: yes
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Install WordNet database
  kewlfft.aur.aur:
    name: wordnet-dictd
  become: yes
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Install Moby thesaurus
  kewlfft.aur.aur:
    name: dict-moby-thesaurus
  become: yes
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Enable and start dictd
  service:
    name: dictd.service
    enabled: yes
    state: started
