---
- name: Install framework-system
  pacman:
    name: framework-system
  tags:
    - framework

- name: Copy charge control service
  copy:
    src: chargecontrol.service
    dest: /etc/systemd/system/
  notify:
    - reload systemd config
    - restart charge control
  tags:
    - framework

- name: Enable and start charge control service
  service:
    name: chargecontrol.service
    enabled: yes
    state: started
  tags:
    - framework
