---
- include_tasks: tlp.yml

- name: Copy touchpad configuration file
  copy:
    src: 30-touchpad.conf
    dest: /etc/X11/xorg.conf.d/30-touchpad.conf
  tags:
    - libinput

- name: Copy logind configuration file
  copy:
    src: logind.conf
    dest: /etc/systemd/logind.conf

- name: Install poweralertd
  aur:
    name: poweralertd
    user: "{{ user.name }}"
  tags:
    - aur

- name: Enable and start poweralertd
  systemd:
    name: poweralertd.service
    scope: user
    enabled: yes
    state: started
  become: yes
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  tags:
    - aur

- name: Install brightnessctl
  pacman:
    name: brightnessctl
    state: present

- name: Install powertop
  pacman:
    name: powertop
    state: present

- name: Install powerstat
  aur:
    name: powerstat
    user: "{{ user.name }}"
  tags:
    - aur

- name: Install cmake for battery-stats
  pacman:
    name: cmake
    state: present

- name: Install battery-stats
  aur:
    name: battery-stats-git
    user: "{{ user.name }}"
  tags:
    - aur

- name: Install battop
  aur:
    name: battop
    user: "{{ user.name }}"
  tags:
    - aur
