---
- name: Install YubiKey Personalization GUI
  pacman: name=yubikey-personalization-gui state=present

- name: Install YubiKey Manager GUI
  pacman: name=yubikey-manager-qt state=present

- name: Install smartcard libs/tools
  pacman:
    name:
      - pcsclite
      - libusb-compat
      - ccid
    state: present
