---
- name: Install GPXSee
  pacman:
    name: gpxsee
    state: present

- name: Install gpxpy
  kewlfft.aur.aur:
    name: python-gpxpy
  become: yes
  become_user: "{{ aur.user }}"
  tags:
    - aur
