---
- name: Install parcimonie.sh
  kewlfft.aur.aur:
    name: parcimonie-sh-git
    use: makepkg
    skip_pgp_check: yes
  become: yes
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Push parcimonie.sh user configuration
  template:
    src: user.conf.j2
    dest: /etc/parcimonie.sh.d/{{ user.name }}.conf

- include_tasks: roles/nmtrust/tasks/unit.yml
  vars:
      unit: "parcimonie.sh@{{ user.name }}.service"
      run_on: "{{ tor.run_on }}"
