---
- name: Install localtime
  kewlfft.aur.aur:
    name: localtime-git
  become: yes
  become_user: "{{ aur.user }}"
  tags:
    - aur

- include_tasks: roles/nmtrust/tasks/unit.yml
  vars:
      unit: localtime.service
      run_on: "{{ localtime.run_on }}"
