---
- name: Install pipenv
  pacman:
      name: python-pipenv
      state: present

- name: Install pyenv
  pacman:
      name: pyenv
      state: present

- name: Install ruff
  pacman:
      name: ruff
      state: present

- name: Install uv
  pacman:
      name: uv
      state: present

- name: Install documentation
  pacman:
      name: python-docs
      state: present
