---
- name: Install beets and dependencies
  pacman:
    name:
      - gst-libav
      - gst-plugins-bad
      - gst-plugins-good
      - gst-plugins-ugly
      - gst-python
      - python-beautifulsoup4
      - python-gobject
      - python-langdetect
      - python-pyacoustid
      - python-pylast
      - python-requests
      - beets
    state: present
  tags:
    - beets

- name: Install mp3val
  kewlfft.aur.aur:
    name: mp3val
  become: yes
  become_user: "{{ aur.user }}"
  tags:
    - aur
    - beets
