---
- name: Install feh
  pacman: name=feh state=present
  tags:
    - feh

- name: Jail feh
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/feh
        state=link
  tags:
    - feh
    - firejail

- name: Install imlib2-heic
  kewlfft.aur.aur:
    name: imlib2-heic
    use: makepkg
    skip_pgp_check: yes
  become: yes
  become_user: "{{ aur.user }}"
  tags:
    - aur
    - feh
