---
- name: Install GNUradio
  pacman: name=gnuradio state=present

- name: Install hamlib
  aur:
    name:
      - perl-opcodes
      - hamlib
    user: "{{ user.name }}"
  tags:
    - aur

- include: rtl-sdr.yml
- include: radio_mgmt.yml
- include: radio_ops.yml
