---
- name: Install fldigi
  kewlfft.aur.aur:
    name:
      - cty
      - flxmlrpc
      - fldigi
      - flrig
  become: yes
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Install wsjtx
  kewlfft.aur.aur:
    name: wsjtx
  become: yes
  become_user: "{{ aur.user }}"
  tags:
    - aur
