---
- name: Install Bash
  pacman:
    name:
      - bash
      - bash-completion
    state: present
  tags:
    - shell

- name: Install ZSH
  pacman:
    name:
      - zsh
      - zsh-completions
    state: present
  tags:
    - shell

- name: Install zsh-antidote
  kewlfft.aur.aur:
    name: zsh-antidote
  become: yes
  become_user: "{{ aur.user }}"
  tags:
    - aur
