---
- name: Install Vopono
  kewlfft.aur.aur:
    name: vopono
  become: yes
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Allow passwordless Vopono for wheel group
  copy:
    src: sudo_vopono
    dest: /etc/sudoers.d/03_vopono
    mode: 440
    validate: 'visudo -cf %s'
  tags:
    - aur
    - sudo
